### ISSUE TITLE
Do not send messages

### ISSUE THREAD

**Issue by matbott** [ANemcov/redmine_telegram#1]
Do not send messages. redmine attached log to help me

`Processing by IssuesController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"0eU5RaWOBjssY2ifTypwo1ztmaIpPk8SHyjHqx79pb0=", "issue"=>{"is_private"=>"0", "tracker_id"=>"3", "subject"=>"prueba telegram", "description"=>"", "status_id"=>"1", "priority_id"=>"2", "assigned_to_id"=>"", "category_id"=>"", "parent_issue_id"=>"", "start_date"=>"2016-02-03", "due_date"=>"", "estimated_hours"=>"", "done_ratio"=>"0", "tag_list"=>""}, "commit"=>"Crear", "project_id"=>"tareas-personal"}
  Current user: Matias (id=5)
TELEGRAM Add Issue [Tareas - Matias - Soporte #6173] (Nueva) prueba telegram
TELEGRAM SPEAK *[Tareas - Matias]* _Matias F._ created [Soporte #6173: prueba telegram](http://10.200.4.86/redmine/issues/6173) => 50553068
telegram_url https://api.telegram.org/bot191379764:AAH4puvYqRNSpk9aVgskBG2g0YfXE8lEKH4/sendMessage
`

**Comment by ANemcov** [comment]
What is your chat_id for chating with bot?
And remove token from text - it is not secure.

**Comment by ANemcov** [comment]
Try to send messages from browser - success.
Can you attach more info (logs, screenshots)?

**Comment by matbott** [comment]
Thanks but I think the company proxy server is blocking me messages to Telegram.
Regards.
The token change it, thank you.
